/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bignum;

import java.math.BigInteger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class BigNumber extends javax.swing.JFrame {

    /**
     * Creates new form BigNumber
     */
    public BigNumber() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfSothu1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFKetqua = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTFSothu2 = new javax.swing.JTextField();
        jlbSothu2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chương trình máy tính");
        setLocation(new java.awt.Point(250, 120));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfSothu1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jtfSothu1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfSothu1.setText("0");
        jtfSothu1.setToolTipText("");
        jtfSothu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtfSothu1MousePressed(evt);
            }
        });
        jtfSothu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSothu1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtfSothu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 393, 64));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Số thứ 1:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 60));

        jTFKetqua.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jTFKetqua.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFKetqua.setText("0");
        jTFKetqua.setToolTipText("");
        jTFKetqua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFKetquaMousePressed(evt);
            }
        });
        getContentPane().add(jTFKetqua, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 393, 64));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Kết quả:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, 60));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Thương");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 110, 50));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("Tổng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 110, 50));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setText("Hiệu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 110, 50));

        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setText("Tích");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 110, 50));

        jTFSothu2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jTFSothu2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFSothu2.setText("0");
        jTFSothu2.setToolTipText("");
        jTFSothu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFSothu2MousePressed(evt);
            }
        });
        jTFSothu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFSothu2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTFSothu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 393, 64));

        jlbSothu2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlbSothu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSothu2.setText("Số thứ 2:");
        getContentPane().add(jlbSothu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, 60));

        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setText("Giai thừa");
        jButton5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton5MouseMoved(evt);
            }
        });
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, 50));

        jButton6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton6.setText("Lũy thừa");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 110, 50));

        jButton7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton7.setText("UCLN");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, 110, 50));

        jButton8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton8.setText("Chia dư");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 110, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        try {
            jTFKetqua.setText((new BigInteger(jtfSothu1.getText()).add(new BigInteger(jTFSothu2.getText()))).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kiểm tra lại đầu vào.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtfSothu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSothu1ActionPerformed
        // TODO add your handling code here:

        jtfSothu1.selectAll();
    }//GEN-LAST:event_jtfSothu1ActionPerformed

    private void jTFSothu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFSothu2ActionPerformed
        // TODO add your handling code here:

        jTFSothu2.selectAll();
    }//GEN-LAST:event_jTFSothu2ActionPerformed

    private void jtfSothu1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfSothu1MousePressed
        // TODO add your handling code here:

        jtfSothu1.selectAll();
    }//GEN-LAST:event_jtfSothu1MousePressed

    private void jTFSothu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFSothu2MousePressed
        // TODO add your handling code here:

        jTFSothu2.selectAll();
    }//GEN-LAST:event_jTFSothu2MousePressed

    private void jTFKetquaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFKetquaMousePressed
        // TODO add your handling code here:

        jTFKetqua.selectAll();
    }//GEN-LAST:event_jTFKetquaMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        try {
            jTFKetqua.setText((new BigInteger(jtfSothu1.getText()).subtract(new BigInteger(jTFSothu2.getText()))).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kiểm tra lại đầu vào.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        try {
            jTFKetqua.setText((new BigInteger(jtfSothu1.getText()).multiply(new BigInteger(jTFSothu2.getText()))).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kiểm tra lại đầu vào.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            jTFKetqua.setText((new BigInteger(jtfSothu1.getText()).divide(new BigInteger(jTFSothu2.getText()))).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kiểm tra lại đầu vào.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        jTFKetqua.setText(giaithua(new BigInteger(jtfSothu1.getText())).toString());
    }//GEN-LAST:event_jButton5ActionPerformed

    private BigInteger giaithua(BigInteger b1) {

        if (b1.compareTo(BigInteger.ONE) < 0) {
            return BigInteger.ONE;
        }
        return b1.multiply(giaithua(b1.subtract(BigInteger.ONE)));
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            jTFKetqua.setText((new BigInteger(jtfSothu1.getText()).pow(Integer.parseInt(jTFSothu2.getText()))).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kiểm tra lại đầu vào.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
            jTFKetqua.setText((new BigInteger(jtfSothu1.getText()).gcd(new BigInteger(jTFSothu2.getText()))).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kiểm tra lại đầu vào.");
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:

        try {
            jTFKetqua.setText((new BigInteger(jtfSothu1.getText()).mod(new BigInteger(jTFSothu2.getText()))).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Kiểm tra lại đầu vào.");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseMoved
        // TODO add your handling code here:

        jlbSothu2.setVisible(false);
        jTFSothu2.setVisible(false);
    }//GEN-LAST:event_jButton5MouseMoved

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        // TODO add your handling code here:

        jlbSothu2.setVisible(true);
        jTFSothu2.setVisible(true);
    }//GEN-LAST:event_jButton5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BigNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BigNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BigNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BigNumber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BigNumber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTFKetqua;
    private javax.swing.JTextField jTFSothu2;
    private javax.swing.JLabel jlbSothu2;
    private javax.swing.JTextField jtfSothu1;
    // End of variables declaration//GEN-END:variables
}
